# {% set goname = "github.com/keycloak/keycloak-gatekeeper" %}
{% set goname = "github.com/louketo/louketo-proxy" %}
{% set version = "1.0.0" %}

{% set name = "keycloak-gatekeeper" %}
{% set pkg_src = ('src/'+goname).replace("/", "\\" if win else "/") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: {{ pkg_src }}
    url: https://{{ goname }}/archive/{{ version }}.tar.gz
    sha256: cb19406a35797165fb135a5152c8e6ace17315f892ad5a3d0e13b89ca9aae2cd
    patches:
      # Parse and Verify the ID Token before trying to use the access-token
      - access_token.patch

build:
  number: 4
  script:
    - pushd {{ pkg_src }}
    - dep ensure
    - patch -p1 -i {{ RECIPE_DIR }}{{ os.sep }}client_secret.patch
    - patch -p1 -i {{ RECIPE_DIR }}{{ os.sep }}rs512.patch
    - go test -v .
    - go install -v .

requirements:
  build:
    - {{ compiler("go") }} >=1.11.3
    - go-dep
    - patch  # [unix]
    - m2-patch  # [win]

test:
  requires:
    - m2-bash  # [win]
  commands:
    - bash -c "{{ name|lower }} -v"

about:
  home: https://github.com/keycloak/keycloak-gatekeeper

  license: Apache 2.0
  license_family: Apache
  license_file: {{ pkg_src }}/LICENSE
  summary: 'An adapter for use with OpenID Connect that supports both access tokens in a browser cookie or bearer tokens'

  description: |
    Keycloak is an open source Identity and Access Management solution aimed
    at modern applications and services. It makes it easy to secure applications
    and services with little to no code. Some of its features include Single-Sign On,
    Identity Brokering and Social Login, User Federation and Client Adapters.
  doc_url: https://www.keycloak.org/docs/latest/securing_apps/index.html#_keycloak_generic_adapter

  dev_url: https://github.com/keycloak/keycloak-gatekeeper

extra:
  recipe-maintainers:
    - adbeda
    - sodre
    - rluria14
    - oblute
